#
# https://kubernetes.io/docs/user-guide/deployments/
# https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_container
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-alglab111
  labels:
    service: vncserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        user: alglab11
        role: gateway
        service: vncserver
    spec:
      containers:
      - name: desktop-ibgateway-alglab111
        image: appsoa/docker-centos-desktop-ibgateway:latest
        ports:
          - containerPort: 5901
          - containerPort: 6901
          - containerPort: 4100
        env:
          - name: CONF_VNC_PASS
            value: 'testing123'
          - name: CONF_CONTROLLER_PORT
            value: '4200'
          - name: CONF_API_PORT
            value: '4100'
          - name: CONF_TRADING_MODE
            value: 'paper'
          - name: CONF_IB_USER
            value: 'alglab111'
          - name: CONF_IB_PASS
            value: 'greg2017'
          - name: CONF_IB_READ_ONLY
            value: 'no'
      - name: desktop-webvnc-alglab111
        image: appsoa/docker-centos-desktop-webvnc:latest
        ports:
          - containerPort: 6901
        env:
          - name: CONF_VNC_HTTP_PORT
            value: '6901'
          - name: CONF_VNC_REMOTE
            value: '146.148.76.226:5901'